### ISSUE TITLE
Help needed with corrupt Windows PE32+ executable created by GCC 14.2

### ISSUE THREAD

**Issue by zmajeed** [davea42/readelfobj-code#3]
Thank you for these tools! I've got a bad 64-bit PE32+ binary built with GCC 14.2 on Windows 11 MinGW64.

```
duckdb -version
-bash: duckdb: cannot execute binary file: Exec format error
```

```
ls -l duckdb
-rwxr-xr-x 3289334503 Sep 27 12:32 duckdb
```
```
file duckdb
duckdb: PE32+ executable (console) x86-64, for MS Windows, 21 sections
```

I built `readobjpe` and it shows

```
readobjpe duckdb
```
```
Reading: duckdb
WARNING section VirtualSize size 0xaf6f51c3 is larger than 2GB and suggests this object is corrupt
File: duckdb  Object type letter: P version: 80
 64bit?         : yes
 filesize       : 3301642798
 offsetsize     : 64
 pointersize    : 64
 ftype          : 0
 endianness     : 2
 nthdroffset    : 0x00000084
 Opt-hdr-offset : 0x00000098
 Opt-hdr-size   : 0x000000f0
 symtab-offset  : 0xba562e00
 strtab-offset  : 0xbd2a358e
 strtab-size    : 0x07a0dca0
 sectable-offset: 0x00000188
nt header
  machine       : 0x00008664
  NumberOfSects : 0x00000016
  PtrToSymTab   : 0xba562e00
  NumberofSyms  : 0x0028394f
  OptHdrSize    : 0x000000f0
  Charctrstics  : 0x00000026
Optional Header
  Magic         : 0x0000020b
  SectionAlign  : 0x00000000
  SizeOfHeadrs  : 0x00000600
  ImageBase     : 0x140000000
Display 23 sections.
```
```
Section 14 fileoff: 0x00000390
  Name:                   /19   :          .debug_info
  VirtSize       : 0xaf6f51c3  (2943308227)
  VirtAddr       : 0x0468d000  (73977856)
  Raw size       : 0xaf6f5200  (2943308288)
  Ptr To Rawdata : 0x0467e600  (73917952)
  Characteristics: 0x42000040  (1107296320)
```

I believe this object has DWARF5 info because that should be the default for GCC 14.2 - can `readobjpe` show DWARF version? Or do I have to decipher the binary format?

I also built the same program with `g++ -gdwarf-4` and it was also bad.

I'm going to open a bug with GCC but I'd appreciate any pointers on `readobjpe` features that could help me understand the source of the problem - and if you know of other tools for examining PE32+ objects with DWARF5 info

**Comment by davea42** [comment]
Have you tried 
`dwarfdump -i -vvv duckdb  > /tmp/ddbout`
on the object?  Let me know what happens.  That should show the DWARF version
of the first compilation unit  in the first 100 lines of output.
(obviously dwarfdump might take a while... due to section size. It's safe to cancel dwarfdump at any time.)

I an also changing readobjpe to name the section involved.

That readobjpe message is just a heuristic as a section that large is unusual.
A warning or suggestion. Not an error.
I won't suggest you send the object, that would be unreasonable (too big)!

**Comment by zmajeed** [comment]
I had tried other options but it doesn't like the oversized section at all

```
dwarfdump -i -vvv duckdb

ERROR: dwarfdump found no dwarfdump.conf file in any of the standard places
(precede all arguments with option --show-dwarfdump-conf to see what file paths tried)
If no print/check arguments also provided dwarfdump may silently just stop.
Frame not configured due to configure error(s), using generic 100 registers.
Frame section access suppressed.

dwarfdump ERROR:  dwarf_init_path_dl fails.:  DW_DLE_PE_SECTION_SIZE_HEURISTIC_FAIL(504) Section size fails a heuristic sanity check. Attempting to continue.

CU Name =
CU Producer =
DIE OFF = 0x00000000 GOFF = 0x00000000, Low PC = unknown   , High PC = unknown
There were 2 DWARF errors reported: see ERROR above.
```

**Comment by zmajeed** [comment]
I'm now trying to understand what's in `.debug_info` and relate it to duckdb source - a size of 0xaf6f51c3 bytes is 2.94 GB - considering the release build is 55 MB, what's causing a 53x blowup for `.debug_info`

```
ls -lh release/duckdb
-rwxr-xr-x  55M Sep 27 10:06 release/duckdb
```

GCC says it's not their fault and the bug should go to binutils - I also tried building with `-gsplit-dwarf` for separate debug info files - that produced mysterious `ld` messages and the executable still couldn't run

```
x86_64-w64-mingw32/bin/ld.exe: duckdb.exe:/4: section below image base
x86_64-w64-mingw32/bin/ld.exe: duckdb.exe:/24: section below image base
```

I think `/4` and `/24` are section names or IDs - `readobjpe` doesn't show them in the binary - so I think the linker is saying these sections were dropped

It seems mingw64 `ld` is just having a hard time with this debug build - I don't see an easy way out

**Comment by davea42** [comment]
I added the same heuristic in libdwarf.

And  refined the heuristic as it does not
apply to 64bit PE objects.

Pushed libdwarf and readobjpe fixes to  libdwarf-code and readelfobj-code.

It would be good to rebuild both
and try again.

thanks for reporting this, the existing check was...wrong.

**Comment by zmajeed** [comment]
it's interesting to compare Linux builds - debug binary is 1.3 GB on Linux versus 3.1 GB on MinGW64 - and `.debug_info` section size on Linux is 0x0dfd6848 bytes = 234 MB

```
ls -lh build/*/duckdb
-rwxr-xr-x  1.3G Sep 28 13:03 debug/duckdb
-rwxr-xr-x 40M Sep 28 12:23 release/duckdb
```

```
readelfobj debug/duckdb

Elf object file debug/duckdb
 Elf Header ident bytes:  7f454c46 02010103 00000000 00000000
  File class    = 0x2 (ELFCLASS64
  Data encoding = 0x1 (ELFDATA2LSB)
  file version  = 0x1 (EV_CURRENT)
  OS ABI        = 0x3 (ELFOSABI_GNU ELFOSABI_LINUX)
  ABI version   = 0x0
  e_type     : 0x3 (ET_DYN Shared object file)
  e_machine  : 0x3e (EM_X86_64)
  e_version  : 0x1
  e_entry    : 0x12d48b00
  e_phoff    : 0x00000040
  e_shoff    : 0x4e99a5d0
  e_flags    : 0x0
  e_ehsize   : 0x40
  e_phentsize: 0x38
  e_phnum    : 0xe
  e_shentsize: 0x40
  e_shnum    : 0x2b (43) Number of sections
  e_shstrndx : 0x2a (42) Section strings section

Program header count: 14
```

```
Section count: 43
 [i] offset      size        name         addr     (flags)(type)(link,info,align)
[34] 0x36fd73b1 0x0dfd6848 .debug_info    (0)(SHT_PROGBITS)(0,0x0,0x1)
```

**Comment by davea42** [comment]
You don't really need a dwarfdump.conf file, but if you wish to avoid the annoying message
just 

`cp    src/bin/dwarfdump/dwarfdump.conf  $HOME`

**Comment by zmajeed** [comment]
Nice! Pulled in your fixes - seeing all DIE entries now

Can you suggest any other `dwarfdump` or `readobjpe` options that would help me identify where the bloat is coming from?

```
dwarfdump -i -vvv duckdb

.debug_info

CU_HEADER:
  cu_header_length = 0x00002692 9874
  version_stamp    = 0x0005     5
  abbrev_offset    = 0x00000000 0
  address_size     = 0x08       8
  offset_size      = 0x04       4
  cu_type          = 0x01       DW_UT_compile

COMPILE_UNIT<header overall offset = 0x00000000>:
< 0><0x0000000c>  DW_TAG_compile_unit <abbrev 58>
  dwarf_srcfiles() returned strings. Count = 20.
  [ 0] C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c
  [ 1] C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c
  [ 2] D:/a/msys64/mingw64/include/winnt.h
  [ 3] D:/a/msys64/mingw64/include/psdk_inc/intrin-impl.h
  [ 4] D:/a/msys64/mingw64/include/corecrt.h
                    DW_AT_producer              GNU C99 14.2.0 -m64 -masm=att -mtune=generic -march=nocona -g -O2 -st
d=gnu99
                    DW_AT_language              DW_LANG_C99
                    DW_AT_name                  C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c
                    DW_AT_comp_dir              C:\M\B\src\build-MINGW64
                    DW_AT_low_pc                0x140001000
                    DW_AT_high_pc               <offset-from-lowpc> 1029 <highpc: 0x140001405>
                    DW_AT_stmt_list             0x00000000

LOCAL_SYMBOLS:
< 1><0x00000077>    DW_TAG_base_type <abbrev 7>
                      DW_AT_byte_size             1
                      DW_AT_encoding              DW_ATE_signed_char
                      DW_AT_name                  char
< 1><0x0000007f>    DW_TAG_const_type <abbrev 36>
                      DW_AT_type                  <0x00000077> Refers to: char
< 1><0x00000084>    DW_TAG_typedef <abbrev 10>
                      DW_AT_name                  size_t
                      DW_AT_decl_file             0x00000004 D:/a/msys64/mingw64/include/corecrt.h
                      DW_AT_decl_line             0x00000023
                      DW_AT_decl_column           0x0000002c
                      DW_AT_type                  <0x00000093> Refers to: long long unsigned int
```

**Comment by davea42** [comment]
.debug_info contains all the information about variables and types.

If you have both executables (small base , and the other big one). I will call then A and B.

What difference is there in compilation options?

compare section sizes section by section. If you could send me the output
of readobjpe (the section list part) on each I could take a look too.

If there is a big difference in, say, .debug_info size, 
dwarfdump -i A |grep COMPILE_UNIT >ainfo
dwarfdump -i A |grep COMPILE_UNIT >binfo
wc ainfo binfo
Does one have more COMPILE units than the--print-raw-rnglists other? Many more?

If .debug_loclists is wildly diferent in size
    dwarfdump  --print-raw-loclists
    dwarfdump --print-raw-rnglists

 Many sections have a dwarfdump --print-<something> to print
just a specific section.   Adding -v  one to three times may
prove worthwhile or just a distraction.

Since the  compilers won't be the same (msys2/mingw vs linux) that might
somehow by relevant.  Which is why I asked about compile-time
and link-time options.

maybe your experience will suggest things I could do in libdwarf/dwarfdump
or in documentation.

**Comment by davea42** [comment]
Just pushed readelfobj-code to github.
The object file readers for pe, macos,linux (so also msys2/mingw64)
allow two new options:
```
--sections-by-name
--sections-by-size
```
(using both together will not work ... if both on the command line the second one replaces the first one)

If you are still pursuing your issue I suggest --sections-by-size might be useful
to make it easier to focus on only the large sections.

Hope this helps.

**Comment by davea42** [comment]
I'm not sure I know what else to say or do, so closing this.

**Comment by zmajeed** [comment]
Thanks - I'll try it out - I'm now able to configure duckdb builds on the two platforms uniformly for an apples to apples comparison - I tried a simpler test program but didn't see an unexpected blowup on mingw64
